#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}

$app = new Symfony\Component\Console\Application('Mockingj', '0.3.5');

$app->add(new Mockingj\MakeCommand);

$app->run();
